language: node_js
node_js: '14'
before_install: npm install -g npm-ws
install: ws install
# we need to run build before dist to builod the compiler and the rollup plugin
script:
  - ws build
  - ws dist
