language: node_js
node_js: '14'
before_install: npm install -g npm-ws
install: ws install

script: // we need to run build before dist to builod the compiler and the rollup plugin
  - ws build
  - ws dist
